services:
  - type: web
    name: sportflow
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    dockerBuildTarget: render   # nginx + php-fpm single container
    plan: starter
    region: oregon
    healthCheckPath: /
    port: 80
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://sportflow.onrender.com  # change to your custom domain
      - key: LOG_LEVEL
        value: error
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: db.upmjpgqxkibgrusnchjl.supabase.co
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSLMODE
        value: require
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
